language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
stages:
  - compile
  - test
  - deploy
jobs:
  include:
    - stage: install-dependencies
      script: yarn install --frozen-lockfile
    - stage: typecheck
      script: yarn typescript
    - stage: unit-tests
      script: yarn test --watchAll=false --coverage